language: node_js

node_js:
  - node

env:
  - YARN_GPG=no

os:
  - linux
  - osx
  - windows

cache: yarn

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip install proselint; fi
  - yarn --frozen-lockfile

script:
  - yarn test
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then yarn workspace website lint; fi
