language: node_js

node_js:
  - node

env:
  - YARN_GPG=no

os:
  - linux
  - osx
  - windows

cache: yarn

install:
  - sudo pip install proselint
  - yarn --frozen-lockfile

script:
  - yarn test
  - yarn lint:prose
