// flow-typed signature: 8ceb707e76e15261b612b32e57ef2863
// flow-typed version: <<STUB>>/@types/commander_v^2.9.2/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/commander'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/commander' {
  declare module.exports: any;
}
