// flow-typed signature: ed47bc9eef77e9720e20d5072d7467c3
// flow-typed version: <<STUB>>/5to6-codemod_v^1.7.1/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   '5to6-codemod'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '5to6-codemod' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '5to6-codemod/test/fixtures/amd.after' {
  declare module.exports: any;
}

declare module '5to6-codemod/test/fixtures/amd.before' {
  declare module.exports: any;
}

declare module '5to6-codemod/test/fixtures/cjs/called.after' {
  declare module.exports: any;
}

declare module '5to6-codemod/test/fixtures/cjs/called.before' {
  declare module.exports: any;
}

declare module '5to6-codemod/test/fixtures/cjs/comments.after' {
  declare module.exports: any;
}

declare module '5to6-codemod/test/fixtures/cjs/comments.before' {
  declare module.exports: any;
}

declare module '5to6-codemod/test/fixtures/cjs/declaration.after' {
  declare module.exports: any;
}

declare module '5to6-codemod/test/fixtures/cjs/declaration.before' {
  declare module.exports: any;
}

declare module '5to6-codemod/test/fixtures/cjs/hoist.after' {
  declare module.exports: any;
}

declare module '5to6-codemod/test/fixtures/cjs/hoist.before' {
  declare module.exports: any;
}

declare module '5to6-codemod/test/fixtures/cjs/ignore.after' {
  declare module.exports: any;
}

declare module '5to6-codemod/test/fixtures/cjs/ignore.before' {
  declare module.exports: any;
}

declare module '5to6-codemod/test/fixtures/cjs/mapper.after' {
  declare module.exports: any;
}

declare module '5to6-codemod/test/fixtures/cjs/mapper.before' {
  declare module.exports: any;
}

declare module '5to6-codemod/test/fixtures/cjs/object.after' {
  declare module.exports: any;
}

declare module '5to6-codemod/test/fixtures/cjs/object.before' {
  declare module.exports: any;
}

declare module '5to6-codemod/test/fixtures/cjs/standalone.after' {
  declare module.exports: any;
}

declare module '5to6-codemod/test/fixtures/cjs/standalone.before' {
  declare module.exports: any;
}

declare module '5to6-codemod/test/fixtures/exports/called.after' {
  declare module.exports: any;
}

declare module '5to6-codemod/test/fixtures/exports/called.before' {
  declare module.exports: any;
}

declare module '5to6-codemod/test/fixtures/exports/default-with-keyed.after' {
  declare module.exports: any;
}

declare module '5to6-codemod/test/fixtures/exports/default-with-keyed.before' {
  declare module.exports: any;
}

declare module '5to6-codemod/test/fixtures/exports/default.after' {
  declare module.exports: any;
}

declare module '5to6-codemod/test/fixtures/exports/default.before' {
  declare module.exports: any;
}

declare module '5to6-codemod/test/fixtures/exports/ignore.after' {
  declare module.exports: any;
}

declare module '5to6-codemod/test/fixtures/exports/ignore.before' {
  declare module.exports: any;
}

declare module '5to6-codemod/test/fixtures/exports/keyed.after' {
  declare module.exports: any;
}

declare module '5to6-codemod/test/fixtures/exports/keyed.before' {
  declare module.exports: any;
}

declare module '5to6-codemod/test/fixtures/import-cleanup/common.after' {
  declare module.exports: any;
}

declare module '5to6-codemod/test/fixtures/import-cleanup/common.before' {
  declare module.exports: any;
}

declare module '5to6-codemod/test/fixtures/let.after' {
  declare module.exports: any;
}

declare module '5to6-codemod/test/fixtures/let.before' {
  declare module.exports: any;
}

declare module '5to6-codemod/test/fixtures/named-export-generation/declared-mutated.after' {
  declare module.exports: any;
}

declare module '5to6-codemod/test/fixtures/named-export-generation/declared-mutated.before' {
  declare module.exports: any;
}

declare module '5to6-codemod/test/fixtures/named-export-generation/declared.after' {
  declare module.exports: any;
}

declare module '5to6-codemod/test/fixtures/named-export-generation/declared.before' {
  declare module.exports: any;
}

declare module '5to6-codemod/test/fixtures/named-export-generation/expression.after' {
  declare module.exports: any;
}

declare module '5to6-codemod/test/fixtures/named-export-generation/expression.before' {
  declare module.exports: any;
}

declare module '5to6-codemod/test/fixtures/named-export-generation/ignore.after' {
  declare module.exports: any;
}

declare module '5to6-codemod/test/fixtures/named-export-generation/ignore.before' {
  declare module.exports: any;
}

declare module '5to6-codemod/test/fixtures/named-export-generation/references.after' {
  declare module.exports: any;
}

declare module '5to6-codemod/test/fixtures/named-export-generation/references.before' {
  declare module.exports: any;
}

declare module '5to6-codemod/test/fixtures/no-strict-closure.after' {
  declare module.exports: any;
}

declare module '5to6-codemod/test/fixtures/no-strict-closure.before' {
  declare module.exports: any;
}

declare module '5to6-codemod/test/fixtures/no-strict.after' {
  declare module.exports: any;
}

declare module '5to6-codemod/test/fixtures/no-strict.before' {
  declare module.exports: any;
}

declare module '5to6-codemod/test/fixtures/simple-arrow.after' {
  declare module.exports: any;
}

declare module '5to6-codemod/test/fixtures/simple-arrow.before' {
  declare module.exports: any;
}

declare module '5to6-codemod/test/transforms/amd' {
  declare module.exports: any;
}

declare module '5to6-codemod/test/transforms/cjs' {
  declare module.exports: any;
}

declare module '5to6-codemod/test/transforms/exports' {
  declare module.exports: any;
}

declare module '5to6-codemod/test/transforms/import-cleanup' {
  declare module.exports: any;
}

declare module '5to6-codemod/test/transforms/let' {
  declare module.exports: any;
}

declare module '5to6-codemod/test/transforms/named-export-generation' {
  declare module.exports: any;
}

declare module '5to6-codemod/test/transforms/no-strict' {
  declare module.exports: any;
}

declare module '5to6-codemod/test/transforms/simple-arrow' {
  declare module.exports: any;
}

declare module '5to6-codemod/test/utils' {
  declare module.exports: any;
}

declare module '5to6-codemod/transforms/amd' {
  declare module.exports: any;
}

declare module '5to6-codemod/transforms/cjs' {
  declare module.exports: any;
}

declare module '5to6-codemod/transforms/exports' {
  declare module.exports: any;
}

declare module '5to6-codemod/transforms/import-cleanup' {
  declare module.exports: any;
}

declare module '5to6-codemod/transforms/let' {
  declare module.exports: any;
}

declare module '5to6-codemod/transforms/named-export-generation' {
  declare module.exports: any;
}

declare module '5to6-codemod/transforms/no-strict' {
  declare module.exports: any;
}

declare module '5to6-codemod/transforms/simple-arrow' {
  declare module.exports: any;
}

declare module '5to6-codemod/utils/main' {
  declare module.exports: any;
}

// Filename aliases
declare module '5to6-codemod/test/fixtures/amd.after.js' {
  declare module.exports: $Exports<'5to6-codemod/test/fixtures/amd.after'>;
}
declare module '5to6-codemod/test/fixtures/amd.before.js' {
  declare module.exports: $Exports<'5to6-codemod/test/fixtures/amd.before'>;
}
declare module '5to6-codemod/test/fixtures/cjs/called.after.js' {
  declare module.exports: $Exports<'5to6-codemod/test/fixtures/cjs/called.after'>;
}
declare module '5to6-codemod/test/fixtures/cjs/called.before.js' {
  declare module.exports: $Exports<'5to6-codemod/test/fixtures/cjs/called.before'>;
}
declare module '5to6-codemod/test/fixtures/cjs/comments.after.js' {
  declare module.exports: $Exports<'5to6-codemod/test/fixtures/cjs/comments.after'>;
}
declare module '5to6-codemod/test/fixtures/cjs/comments.before.js' {
  declare module.exports: $Exports<'5to6-codemod/test/fixtures/cjs/comments.before'>;
}
declare module '5to6-codemod/test/fixtures/cjs/declaration.after.js' {
  declare module.exports: $Exports<'5to6-codemod/test/fixtures/cjs/declaration.after'>;
}
declare module '5to6-codemod/test/fixtures/cjs/declaration.before.js' {
  declare module.exports: $Exports<'5to6-codemod/test/fixtures/cjs/declaration.before'>;
}
declare module '5to6-codemod/test/fixtures/cjs/hoist.after.js' {
  declare module.exports: $Exports<'5to6-codemod/test/fixtures/cjs/hoist.after'>;
}
declare module '5to6-codemod/test/fixtures/cjs/hoist.before.js' {
  declare module.exports: $Exports<'5to6-codemod/test/fixtures/cjs/hoist.before'>;
}
declare module '5to6-codemod/test/fixtures/cjs/ignore.after.js' {
  declare module.exports: $Exports<'5to6-codemod/test/fixtures/cjs/ignore.after'>;
}
declare module '5to6-codemod/test/fixtures/cjs/ignore.before.js' {
  declare module.exports: $Exports<'5to6-codemod/test/fixtures/cjs/ignore.before'>;
}
declare module '5to6-codemod/test/fixtures/cjs/mapper.after.js' {
  declare module.exports: $Exports<'5to6-codemod/test/fixtures/cjs/mapper.after'>;
}
declare module '5to6-codemod/test/fixtures/cjs/mapper.before.js' {
  declare module.exports: $Exports<'5to6-codemod/test/fixtures/cjs/mapper.before'>;
}
declare module '5to6-codemod/test/fixtures/cjs/object.after.js' {
  declare module.exports: $Exports<'5to6-codemod/test/fixtures/cjs/object.after'>;
}
declare module '5to6-codemod/test/fixtures/cjs/object.before.js' {
  declare module.exports: $Exports<'5to6-codemod/test/fixtures/cjs/object.before'>;
}
declare module '5to6-codemod/test/fixtures/cjs/standalone.after.js' {
  declare module.exports: $Exports<'5to6-codemod/test/fixtures/cjs/standalone.after'>;
}
declare module '5to6-codemod/test/fixtures/cjs/standalone.before.js' {
  declare module.exports: $Exports<'5to6-codemod/test/fixtures/cjs/standalone.before'>;
}
declare module '5to6-codemod/test/fixtures/exports/called.after.js' {
  declare module.exports: $Exports<'5to6-codemod/test/fixtures/exports/called.after'>;
}
declare module '5to6-codemod/test/fixtures/exports/called.before.js' {
  declare module.exports: $Exports<'5to6-codemod/test/fixtures/exports/called.before'>;
}
declare module '5to6-codemod/test/fixtures/exports/default-with-keyed.after.js' {
  declare module.exports: $Exports<'5to6-codemod/test/fixtures/exports/default-with-keyed.after'>;
}
declare module '5to6-codemod/test/fixtures/exports/default-with-keyed.before.js' {
  declare module.exports: $Exports<'5to6-codemod/test/fixtures/exports/default-with-keyed.before'>;
}
declare module '5to6-codemod/test/fixtures/exports/default.after.js' {
  declare module.exports: $Exports<'5to6-codemod/test/fixtures/exports/default.after'>;
}
declare module '5to6-codemod/test/fixtures/exports/default.before.js' {
  declare module.exports: $Exports<'5to6-codemod/test/fixtures/exports/default.before'>;
}
declare module '5to6-codemod/test/fixtures/exports/ignore.after.js' {
  declare module.exports: $Exports<'5to6-codemod/test/fixtures/exports/ignore.after'>;
}
declare module '5to6-codemod/test/fixtures/exports/ignore.before.js' {
  declare module.exports: $Exports<'5to6-codemod/test/fixtures/exports/ignore.before'>;
}
declare module '5to6-codemod/test/fixtures/exports/keyed.after.js' {
  declare module.exports: $Exports<'5to6-codemod/test/fixtures/exports/keyed.after'>;
}
declare module '5to6-codemod/test/fixtures/exports/keyed.before.js' {
  declare module.exports: $Exports<'5to6-codemod/test/fixtures/exports/keyed.before'>;
}
declare module '5to6-codemod/test/fixtures/import-cleanup/common.after.js' {
  declare module.exports: $Exports<'5to6-codemod/test/fixtures/import-cleanup/common.after'>;
}
declare module '5to6-codemod/test/fixtures/import-cleanup/common.before.js' {
  declare module.exports: $Exports<'5to6-codemod/test/fixtures/import-cleanup/common.before'>;
}
declare module '5to6-codemod/test/fixtures/let.after.js' {
  declare module.exports: $Exports<'5to6-codemod/test/fixtures/let.after'>;
}
declare module '5to6-codemod/test/fixtures/let.before.js' {
  declare module.exports: $Exports<'5to6-codemod/test/fixtures/let.before'>;
}
declare module '5to6-codemod/test/fixtures/named-export-generation/declared-mutated.after.js' {
  declare module.exports: $Exports<'5to6-codemod/test/fixtures/named-export-generation/declared-mutated.after'>;
}
declare module '5to6-codemod/test/fixtures/named-export-generation/declared-mutated.before.js' {
  declare module.exports: $Exports<'5to6-codemod/test/fixtures/named-export-generation/declared-mutated.before'>;
}
declare module '5to6-codemod/test/fixtures/named-export-generation/declared.after.js' {
  declare module.exports: $Exports<'5to6-codemod/test/fixtures/named-export-generation/declared.after'>;
}
declare module '5to6-codemod/test/fixtures/named-export-generation/declared.before.js' {
  declare module.exports: $Exports<'5to6-codemod/test/fixtures/named-export-generation/declared.before'>;
}
declare module '5to6-codemod/test/fixtures/named-export-generation/expression.after.js' {
  declare module.exports: $Exports<'5to6-codemod/test/fixtures/named-export-generation/expression.after'>;
}
declare module '5to6-codemod/test/fixtures/named-export-generation/expression.before.js' {
  declare module.exports: $Exports<'5to6-codemod/test/fixtures/named-export-generation/expression.before'>;
}
declare module '5to6-codemod/test/fixtures/named-export-generation/ignore.after.js' {
  declare module.exports: $Exports<'5to6-codemod/test/fixtures/named-export-generation/ignore.after'>;
}
declare module '5to6-codemod/test/fixtures/named-export-generation/ignore.before.js' {
  declare module.exports: $Exports<'5to6-codemod/test/fixtures/named-export-generation/ignore.before'>;
}
declare module '5to6-codemod/test/fixtures/named-export-generation/references.after.js' {
  declare module.exports: $Exports<'5to6-codemod/test/fixtures/named-export-generation/references.after'>;
}
declare module '5to6-codemod/test/fixtures/named-export-generation/references.before.js' {
  declare module.exports: $Exports<'5to6-codemod/test/fixtures/named-export-generation/references.before'>;
}
declare module '5to6-codemod/test/fixtures/no-strict-closure.after.js' {
  declare module.exports: $Exports<'5to6-codemod/test/fixtures/no-strict-closure.after'>;
}
declare module '5to6-codemod/test/fixtures/no-strict-closure.before.js' {
  declare module.exports: $Exports<'5to6-codemod/test/fixtures/no-strict-closure.before'>;
}
declare module '5to6-codemod/test/fixtures/no-strict.after.js' {
  declare module.exports: $Exports<'5to6-codemod/test/fixtures/no-strict.after'>;
}
declare module '5to6-codemod/test/fixtures/no-strict.before.js' {
  declare module.exports: $Exports<'5to6-codemod/test/fixtures/no-strict.before'>;
}
declare module '5to6-codemod/test/fixtures/simple-arrow.after.js' {
  declare module.exports: $Exports<'5to6-codemod/test/fixtures/simple-arrow.after'>;
}
declare module '5to6-codemod/test/fixtures/simple-arrow.before.js' {
  declare module.exports: $Exports<'5to6-codemod/test/fixtures/simple-arrow.before'>;
}
declare module '5to6-codemod/test/transforms/amd.js' {
  declare module.exports: $Exports<'5to6-codemod/test/transforms/amd'>;
}
declare module '5to6-codemod/test/transforms/cjs.js' {
  declare module.exports: $Exports<'5to6-codemod/test/transforms/cjs'>;
}
declare module '5to6-codemod/test/transforms/exports.js' {
  declare module.exports: $Exports<'5to6-codemod/test/transforms/exports'>;
}
declare module '5to6-codemod/test/transforms/import-cleanup.js' {
  declare module.exports: $Exports<'5to6-codemod/test/transforms/import-cleanup'>;
}
declare module '5to6-codemod/test/transforms/let.js' {
  declare module.exports: $Exports<'5to6-codemod/test/transforms/let'>;
}
declare module '5to6-codemod/test/transforms/named-export-generation.js' {
  declare module.exports: $Exports<'5to6-codemod/test/transforms/named-export-generation'>;
}
declare module '5to6-codemod/test/transforms/no-strict.js' {
  declare module.exports: $Exports<'5to6-codemod/test/transforms/no-strict'>;
}
declare module '5to6-codemod/test/transforms/simple-arrow.js' {
  declare module.exports: $Exports<'5to6-codemod/test/transforms/simple-arrow'>;
}
declare module '5to6-codemod/test/utils.js' {
  declare module.exports: $Exports<'5to6-codemod/test/utils'>;
}
declare module '5to6-codemod/transforms/amd.js' {
  declare module.exports: $Exports<'5to6-codemod/transforms/amd'>;
}
declare module '5to6-codemod/transforms/cjs.js' {
  declare module.exports: $Exports<'5to6-codemod/transforms/cjs'>;
}
declare module '5to6-codemod/transforms/exports.js' {
  declare module.exports: $Exports<'5to6-codemod/transforms/exports'>;
}
declare module '5to6-codemod/transforms/import-cleanup.js' {
  declare module.exports: $Exports<'5to6-codemod/transforms/import-cleanup'>;
}
declare module '5to6-codemod/transforms/let.js' {
  declare module.exports: $Exports<'5to6-codemod/transforms/let'>;
}
declare module '5to6-codemod/transforms/named-export-generation.js' {
  declare module.exports: $Exports<'5to6-codemod/transforms/named-export-generation'>;
}
declare module '5to6-codemod/transforms/no-strict.js' {
  declare module.exports: $Exports<'5to6-codemod/transforms/no-strict'>;
}
declare module '5to6-codemod/transforms/simple-arrow.js' {
  declare module.exports: $Exports<'5to6-codemod/transforms/simple-arrow'>;
}
declare module '5to6-codemod/utils/main.js' {
  declare module.exports: $Exports<'5to6-codemod/utils/main'>;
}
