// flow-typed signature: c9542f7fa0d674aac3451b44fa255696
// flow-typed version: <<STUB>>/cjs-to-es6_v^1.0.1/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cjs-to-es6'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cjs-to-es6' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'cjs-to-es6/index' {
  declare module.exports: $Exports<'cjs-to-es6'>;
}
declare module 'cjs-to-es6/index.js' {
  declare module.exports: $Exports<'cjs-to-es6'>;
}
