// flow-typed signature: ee507c44c28c026a293b58043537d3e2
// flow-typed version: <<STUB>>/eslint-config-bliss_v^1.0.14/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-bliss'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-bliss' {
  declare module.exports: any;
}
