// flow-typed signature: 326fd703e501ab34435be659e0b666cf
// flow-typed version: <<STUB>>/eslint-config-bliss_v^1.0.17/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-bliss'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-bliss' {
  declare module.exports: any;
}
