// flow-typed signature: 667b95d4ebfc1d7f51779f72e16c2646
// flow-typed version: <<STUB>>/eslint-config-bliss_v^3.0.0/flow_v0.85.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-bliss'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-bliss' {
  declare module.exports: any;
}
