// flow-typed signature: 2c83b52fe80f9316f757477a3077568c
// flow-typed version: <<STUB>>/findit_v^2.0.0/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'findit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'findit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'findit/example/emitter' {
  declare module.exports: any;
}

declare module 'findit/test/empty' {
  declare module.exports: any;
}

declare module 'findit/test/err' {
  declare module.exports: any;
}

declare module 'findit/test/foo' {
  declare module.exports: any;
}

declare module 'findit/test/module' {
  declare module.exports: any;
}

declare module 'findit/test/stop' {
  declare module.exports: any;
}

declare module 'findit/test/symlinks' {
  declare module.exports: any;
}

// Filename aliases
declare module 'findit/example/emitter.js' {
  declare module.exports: $Exports<'findit/example/emitter'>;
}
declare module 'findit/index' {
  declare module.exports: $Exports<'findit'>;
}
declare module 'findit/index.js' {
  declare module.exports: $Exports<'findit'>;
}
declare module 'findit/test/empty.js' {
  declare module.exports: $Exports<'findit/test/empty'>;
}
declare module 'findit/test/err.js' {
  declare module.exports: $Exports<'findit/test/err'>;
}
declare module 'findit/test/foo.js' {
  declare module.exports: $Exports<'findit/test/foo'>;
}
declare module 'findit/test/module.js' {
  declare module.exports: $Exports<'findit/test/module'>;
}
declare module 'findit/test/stop.js' {
  declare module.exports: $Exports<'findit/test/stop'>;
}
declare module 'findit/test/symlinks.js' {
  declare module.exports: $Exports<'findit/test/symlinks'>;
}
