// flow-typed signature: b644b2abf04ba7e61fe13e5edd0b3ef3
// flow-typed version: <<STUB>>/gitignore-parser_v^0.0.2/flow_v0.85.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gitignore-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gitignore-parser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gitignore-parser/lib/index' {
  declare module.exports: any;
}

declare module 'gitignore-parser/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gitignore-parser/lib/index.js' {
  declare module.exports: $Exports<'gitignore-parser/lib/index'>;
}
declare module 'gitignore-parser/test/index.js' {
  declare module.exports: $Exports<'gitignore-parser/test/index'>;
}
