// flow-typed signature: c331ece1a7bd70ac87a7617d21225a5c
// flow-typed version: <<STUB>>/pkg_v^4.2.5/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pkg'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pkg' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pkg/dictionary/angular-bridge' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/any-promise' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/async' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/aws-sdk' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/babel-core' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/batch' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/bcrypt' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/bignum' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/bindings' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/body-parser' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/browserify' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/bson' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/buffermaker' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/bunyan' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/busboy' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/bytes' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/callsites' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/chokidar' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/coffee-script' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/colors' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/compression' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/connect-mongo' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/connect-mongodb' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/connect-redis' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/connect' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/consolidate' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/cookie-parser' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/cookie' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/copy-paste' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/cors' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/cron' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/cross-env' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/cross-spawn-async' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/curve25519' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/data-preflight' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/debug' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/denymount' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/diff' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/drivelist' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/ed25519' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/ejs' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/elasticsearch' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/electron' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/emailjs' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/engine.io' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/epoll' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/errorhandler' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/errors' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/eslint' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/etcher-image-write' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/exceljs' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/express-load' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/express-session' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/express' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/extender' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/extsprintf' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/faye-websocket' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/feathers' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/findup-sync' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/floordate' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/fmt' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/formidable' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/fs-extra' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/fsevents' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/geoip-lite' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/github' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/gm' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/google-closure-compiler' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/googleapis' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/got' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/graceful-fs' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/grpc' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/gulp' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/hap-nodejs' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/heapdump' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/hoek' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/homebridge' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/http-proxy' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/http-server' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/image-size' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/indexof' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/inquirer' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/j' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/jade' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/jsdom' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/json-stringify-date' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/json-stringify-safe' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/jsonwebtoken' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/kerberos' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/knex' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/later' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/level' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/leveldown' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/levelup' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/liftoff' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/lodash' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/log4js' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/machinepack-urls' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/markdown' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/mdns' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/method-override' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/mime-types' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/mime' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/minimatch' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/minstache' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/module-deps' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/moment-timezone' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/moment' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/mongodb-core' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/mongodb' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/mongoose' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/mongoskin' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/ms' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/msgpack' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/multer' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/muri' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/native-or-bluebird' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/natives' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/nconf' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/nedb' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/negotiator' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/newrelic' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/nib' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/nightmare' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/node-forge' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/node-libcurl' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/node-notifier' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/node-pre-gyp' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/node-redis-pubsub' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/node-sass' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/node-uuid' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/node-xlsx' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/node-zookeeper-client' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/nodegit' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/nodemailer-sendmail-transport' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/nodemailer' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/npm-registry-client' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/npm' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/nssocket' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/oauth2orize' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/octobat' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/opn' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/optimist' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/passport-local' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/passport' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/pg-cursor' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/pg-query-stream' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/pg-types' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/pg' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/pg.js' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/pgpass' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/phantom' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/phantomjs-prebuilt' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/pkginfo' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/pm2' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/pmx' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/pouchdb' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/primus-emitter' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/primus-spark-latency' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/primus' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/publicsuffixlist' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/pug' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/punt' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/puppeteer' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/pwd' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/q' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/raven' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/rc' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/readable-stream' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/rechoir' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/redis-parser' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/redis' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/regression' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/reload' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/request' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/require_optional' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/require-uncached' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/s3' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/safe_datejs' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/sails' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/sax' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/scrypt' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/semver' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/sequelize' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/serialport' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/sha3' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/sharp' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/shelljs' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/sinon' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/socket.io-client' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/socket.io' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/sqlite3' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/steam-crypto' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/steam-resources' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/steam' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/stripe-webhook-middleware' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/stripe' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/strong-globalize' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/stylus' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/supervisor' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/tabtab' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/tesseract.js' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/throng' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/time' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/tmp' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/transformers' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/uglify-js' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/umd' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/underscore' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/union' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/update-notifier' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/usage' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/v8flags' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/verror' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/voc' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/winston-uber' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/winston' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/ws' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/xlsx' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/xml2js' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/yargs' {
  declare module.exports: any;
}

declare module 'pkg/dictionary/zeromq' {
  declare module.exports: any;
}

declare module 'pkg/lib-es5/bin' {
  declare module.exports: any;
}

declare module 'pkg/lib-es5/chmod' {
  declare module.exports: any;
}

declare module 'pkg/lib-es5/detector' {
  declare module.exports: any;
}

declare module 'pkg/lib-es5/fabricator' {
  declare module.exports: any;
}

declare module 'pkg/lib-es5/follow' {
  declare module.exports: any;
}

declare module 'pkg/lib-es5/help' {
  declare module.exports: any;
}

declare module 'pkg/lib-es5/index' {
  declare module.exports: any;
}

declare module 'pkg/lib-es5/log' {
  declare module.exports: any;
}

declare module 'pkg/lib-es5/natives' {
  declare module.exports: any;
}

declare module 'pkg/lib-es5/packer' {
  declare module.exports: any;
}

declare module 'pkg/lib-es5/producer' {
  declare module.exports: any;
}

declare module 'pkg/lib-es5/refiner' {
  declare module.exports: any;
}

declare module 'pkg/lib-es5/walker' {
  declare module.exports: any;
}

declare module 'pkg/prelude/bootstrap' {
  declare module.exports: any;
}

declare module 'pkg/prelude/common' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pkg/dictionary/angular-bridge.js' {
  declare module.exports: $Exports<'pkg/dictionary/angular-bridge'>;
}
declare module 'pkg/dictionary/any-promise.js' {
  declare module.exports: $Exports<'pkg/dictionary/any-promise'>;
}
declare module 'pkg/dictionary/async.js' {
  declare module.exports: $Exports<'pkg/dictionary/async'>;
}
declare module 'pkg/dictionary/aws-sdk.js' {
  declare module.exports: $Exports<'pkg/dictionary/aws-sdk'>;
}
declare module 'pkg/dictionary/babel-core.js' {
  declare module.exports: $Exports<'pkg/dictionary/babel-core'>;
}
declare module 'pkg/dictionary/batch.js' {
  declare module.exports: $Exports<'pkg/dictionary/batch'>;
}
declare module 'pkg/dictionary/bcrypt.js' {
  declare module.exports: $Exports<'pkg/dictionary/bcrypt'>;
}
declare module 'pkg/dictionary/bignum.js' {
  declare module.exports: $Exports<'pkg/dictionary/bignum'>;
}
declare module 'pkg/dictionary/bindings.js' {
  declare module.exports: $Exports<'pkg/dictionary/bindings'>;
}
declare module 'pkg/dictionary/body-parser.js' {
  declare module.exports: $Exports<'pkg/dictionary/body-parser'>;
}
declare module 'pkg/dictionary/browserify.js' {
  declare module.exports: $Exports<'pkg/dictionary/browserify'>;
}
declare module 'pkg/dictionary/bson.js' {
  declare module.exports: $Exports<'pkg/dictionary/bson'>;
}
declare module 'pkg/dictionary/buffermaker.js' {
  declare module.exports: $Exports<'pkg/dictionary/buffermaker'>;
}
declare module 'pkg/dictionary/bunyan.js' {
  declare module.exports: $Exports<'pkg/dictionary/bunyan'>;
}
declare module 'pkg/dictionary/busboy.js' {
  declare module.exports: $Exports<'pkg/dictionary/busboy'>;
}
declare module 'pkg/dictionary/bytes.js' {
  declare module.exports: $Exports<'pkg/dictionary/bytes'>;
}
declare module 'pkg/dictionary/callsites.js' {
  declare module.exports: $Exports<'pkg/dictionary/callsites'>;
}
declare module 'pkg/dictionary/chokidar.js' {
  declare module.exports: $Exports<'pkg/dictionary/chokidar'>;
}
declare module 'pkg/dictionary/coffee-script.js' {
  declare module.exports: $Exports<'pkg/dictionary/coffee-script'>;
}
declare module 'pkg/dictionary/colors.js' {
  declare module.exports: $Exports<'pkg/dictionary/colors'>;
}
declare module 'pkg/dictionary/compression.js' {
  declare module.exports: $Exports<'pkg/dictionary/compression'>;
}
declare module 'pkg/dictionary/connect-mongo.js' {
  declare module.exports: $Exports<'pkg/dictionary/connect-mongo'>;
}
declare module 'pkg/dictionary/connect-mongodb.js' {
  declare module.exports: $Exports<'pkg/dictionary/connect-mongodb'>;
}
declare module 'pkg/dictionary/connect-redis.js' {
  declare module.exports: $Exports<'pkg/dictionary/connect-redis'>;
}
declare module 'pkg/dictionary/connect.js' {
  declare module.exports: $Exports<'pkg/dictionary/connect'>;
}
declare module 'pkg/dictionary/consolidate.js' {
  declare module.exports: $Exports<'pkg/dictionary/consolidate'>;
}
declare module 'pkg/dictionary/cookie-parser.js' {
  declare module.exports: $Exports<'pkg/dictionary/cookie-parser'>;
}
declare module 'pkg/dictionary/cookie.js' {
  declare module.exports: $Exports<'pkg/dictionary/cookie'>;
}
declare module 'pkg/dictionary/copy-paste.js' {
  declare module.exports: $Exports<'pkg/dictionary/copy-paste'>;
}
declare module 'pkg/dictionary/cors.js' {
  declare module.exports: $Exports<'pkg/dictionary/cors'>;
}
declare module 'pkg/dictionary/cron.js' {
  declare module.exports: $Exports<'pkg/dictionary/cron'>;
}
declare module 'pkg/dictionary/cross-env.js' {
  declare module.exports: $Exports<'pkg/dictionary/cross-env'>;
}
declare module 'pkg/dictionary/cross-spawn-async.js' {
  declare module.exports: $Exports<'pkg/dictionary/cross-spawn-async'>;
}
declare module 'pkg/dictionary/curve25519.js' {
  declare module.exports: $Exports<'pkg/dictionary/curve25519'>;
}
declare module 'pkg/dictionary/data-preflight.js' {
  declare module.exports: $Exports<'pkg/dictionary/data-preflight'>;
}
declare module 'pkg/dictionary/debug.js' {
  declare module.exports: $Exports<'pkg/dictionary/debug'>;
}
declare module 'pkg/dictionary/denymount.js' {
  declare module.exports: $Exports<'pkg/dictionary/denymount'>;
}
declare module 'pkg/dictionary/diff.js' {
  declare module.exports: $Exports<'pkg/dictionary/diff'>;
}
declare module 'pkg/dictionary/drivelist.js' {
  declare module.exports: $Exports<'pkg/dictionary/drivelist'>;
}
declare module 'pkg/dictionary/ed25519.js' {
  declare module.exports: $Exports<'pkg/dictionary/ed25519'>;
}
declare module 'pkg/dictionary/ejs.js' {
  declare module.exports: $Exports<'pkg/dictionary/ejs'>;
}
declare module 'pkg/dictionary/elasticsearch.js' {
  declare module.exports: $Exports<'pkg/dictionary/elasticsearch'>;
}
declare module 'pkg/dictionary/electron.js' {
  declare module.exports: $Exports<'pkg/dictionary/electron'>;
}
declare module 'pkg/dictionary/emailjs.js' {
  declare module.exports: $Exports<'pkg/dictionary/emailjs'>;
}
declare module 'pkg/dictionary/engine.io.js' {
  declare module.exports: $Exports<'pkg/dictionary/engine.io'>;
}
declare module 'pkg/dictionary/epoll.js' {
  declare module.exports: $Exports<'pkg/dictionary/epoll'>;
}
declare module 'pkg/dictionary/errorhandler.js' {
  declare module.exports: $Exports<'pkg/dictionary/errorhandler'>;
}
declare module 'pkg/dictionary/errors.js' {
  declare module.exports: $Exports<'pkg/dictionary/errors'>;
}
declare module 'pkg/dictionary/eslint.js' {
  declare module.exports: $Exports<'pkg/dictionary/eslint'>;
}
declare module 'pkg/dictionary/etcher-image-write.js' {
  declare module.exports: $Exports<'pkg/dictionary/etcher-image-write'>;
}
declare module 'pkg/dictionary/exceljs.js' {
  declare module.exports: $Exports<'pkg/dictionary/exceljs'>;
}
declare module 'pkg/dictionary/express-load.js' {
  declare module.exports: $Exports<'pkg/dictionary/express-load'>;
}
declare module 'pkg/dictionary/express-session.js' {
  declare module.exports: $Exports<'pkg/dictionary/express-session'>;
}
declare module 'pkg/dictionary/express.js' {
  declare module.exports: $Exports<'pkg/dictionary/express'>;
}
declare module 'pkg/dictionary/extender.js' {
  declare module.exports: $Exports<'pkg/dictionary/extender'>;
}
declare module 'pkg/dictionary/extsprintf.js' {
  declare module.exports: $Exports<'pkg/dictionary/extsprintf'>;
}
declare module 'pkg/dictionary/faye-websocket.js' {
  declare module.exports: $Exports<'pkg/dictionary/faye-websocket'>;
}
declare module 'pkg/dictionary/feathers.js' {
  declare module.exports: $Exports<'pkg/dictionary/feathers'>;
}
declare module 'pkg/dictionary/findup-sync.js' {
  declare module.exports: $Exports<'pkg/dictionary/findup-sync'>;
}
declare module 'pkg/dictionary/floordate.js' {
  declare module.exports: $Exports<'pkg/dictionary/floordate'>;
}
declare module 'pkg/dictionary/fmt.js' {
  declare module.exports: $Exports<'pkg/dictionary/fmt'>;
}
declare module 'pkg/dictionary/formidable.js' {
  declare module.exports: $Exports<'pkg/dictionary/formidable'>;
}
declare module 'pkg/dictionary/fs-extra.js' {
  declare module.exports: $Exports<'pkg/dictionary/fs-extra'>;
}
declare module 'pkg/dictionary/fsevents.js' {
  declare module.exports: $Exports<'pkg/dictionary/fsevents'>;
}
declare module 'pkg/dictionary/geoip-lite.js' {
  declare module.exports: $Exports<'pkg/dictionary/geoip-lite'>;
}
declare module 'pkg/dictionary/github.js' {
  declare module.exports: $Exports<'pkg/dictionary/github'>;
}
declare module 'pkg/dictionary/gm.js' {
  declare module.exports: $Exports<'pkg/dictionary/gm'>;
}
declare module 'pkg/dictionary/google-closure-compiler.js' {
  declare module.exports: $Exports<'pkg/dictionary/google-closure-compiler'>;
}
declare module 'pkg/dictionary/googleapis.js' {
  declare module.exports: $Exports<'pkg/dictionary/googleapis'>;
}
declare module 'pkg/dictionary/got.js' {
  declare module.exports: $Exports<'pkg/dictionary/got'>;
}
declare module 'pkg/dictionary/graceful-fs.js' {
  declare module.exports: $Exports<'pkg/dictionary/graceful-fs'>;
}
declare module 'pkg/dictionary/grpc.js' {
  declare module.exports: $Exports<'pkg/dictionary/grpc'>;
}
declare module 'pkg/dictionary/gulp.js' {
  declare module.exports: $Exports<'pkg/dictionary/gulp'>;
}
declare module 'pkg/dictionary/hap-nodejs.js' {
  declare module.exports: $Exports<'pkg/dictionary/hap-nodejs'>;
}
declare module 'pkg/dictionary/heapdump.js' {
  declare module.exports: $Exports<'pkg/dictionary/heapdump'>;
}
declare module 'pkg/dictionary/hoek.js' {
  declare module.exports: $Exports<'pkg/dictionary/hoek'>;
}
declare module 'pkg/dictionary/homebridge.js' {
  declare module.exports: $Exports<'pkg/dictionary/homebridge'>;
}
declare module 'pkg/dictionary/http-proxy.js' {
  declare module.exports: $Exports<'pkg/dictionary/http-proxy'>;
}
declare module 'pkg/dictionary/http-server.js' {
  declare module.exports: $Exports<'pkg/dictionary/http-server'>;
}
declare module 'pkg/dictionary/image-size.js' {
  declare module.exports: $Exports<'pkg/dictionary/image-size'>;
}
declare module 'pkg/dictionary/indexof.js' {
  declare module.exports: $Exports<'pkg/dictionary/indexof'>;
}
declare module 'pkg/dictionary/inquirer.js' {
  declare module.exports: $Exports<'pkg/dictionary/inquirer'>;
}
declare module 'pkg/dictionary/j.js' {
  declare module.exports: $Exports<'pkg/dictionary/j'>;
}
declare module 'pkg/dictionary/jade.js' {
  declare module.exports: $Exports<'pkg/dictionary/jade'>;
}
declare module 'pkg/dictionary/jsdom.js' {
  declare module.exports: $Exports<'pkg/dictionary/jsdom'>;
}
declare module 'pkg/dictionary/json-stringify-date.js' {
  declare module.exports: $Exports<'pkg/dictionary/json-stringify-date'>;
}
declare module 'pkg/dictionary/json-stringify-safe.js' {
  declare module.exports: $Exports<'pkg/dictionary/json-stringify-safe'>;
}
declare module 'pkg/dictionary/jsonwebtoken.js' {
  declare module.exports: $Exports<'pkg/dictionary/jsonwebtoken'>;
}
declare module 'pkg/dictionary/kerberos.js' {
  declare module.exports: $Exports<'pkg/dictionary/kerberos'>;
}
declare module 'pkg/dictionary/knex.js' {
  declare module.exports: $Exports<'pkg/dictionary/knex'>;
}
declare module 'pkg/dictionary/later.js' {
  declare module.exports: $Exports<'pkg/dictionary/later'>;
}
declare module 'pkg/dictionary/level.js' {
  declare module.exports: $Exports<'pkg/dictionary/level'>;
}
declare module 'pkg/dictionary/leveldown.js' {
  declare module.exports: $Exports<'pkg/dictionary/leveldown'>;
}
declare module 'pkg/dictionary/levelup.js' {
  declare module.exports: $Exports<'pkg/dictionary/levelup'>;
}
declare module 'pkg/dictionary/liftoff.js' {
  declare module.exports: $Exports<'pkg/dictionary/liftoff'>;
}
declare module 'pkg/dictionary/lodash.js' {
  declare module.exports: $Exports<'pkg/dictionary/lodash'>;
}
declare module 'pkg/dictionary/log4js.js' {
  declare module.exports: $Exports<'pkg/dictionary/log4js'>;
}
declare module 'pkg/dictionary/machinepack-urls.js' {
  declare module.exports: $Exports<'pkg/dictionary/machinepack-urls'>;
}
declare module 'pkg/dictionary/markdown.js' {
  declare module.exports: $Exports<'pkg/dictionary/markdown'>;
}
declare module 'pkg/dictionary/mdns.js' {
  declare module.exports: $Exports<'pkg/dictionary/mdns'>;
}
declare module 'pkg/dictionary/method-override.js' {
  declare module.exports: $Exports<'pkg/dictionary/method-override'>;
}
declare module 'pkg/dictionary/mime-types.js' {
  declare module.exports: $Exports<'pkg/dictionary/mime-types'>;
}
declare module 'pkg/dictionary/mime.js' {
  declare module.exports: $Exports<'pkg/dictionary/mime'>;
}
declare module 'pkg/dictionary/minimatch.js' {
  declare module.exports: $Exports<'pkg/dictionary/minimatch'>;
}
declare module 'pkg/dictionary/minstache.js' {
  declare module.exports: $Exports<'pkg/dictionary/minstache'>;
}
declare module 'pkg/dictionary/module-deps.js' {
  declare module.exports: $Exports<'pkg/dictionary/module-deps'>;
}
declare module 'pkg/dictionary/moment-timezone.js' {
  declare module.exports: $Exports<'pkg/dictionary/moment-timezone'>;
}
declare module 'pkg/dictionary/moment.js' {
  declare module.exports: $Exports<'pkg/dictionary/moment'>;
}
declare module 'pkg/dictionary/mongodb-core.js' {
  declare module.exports: $Exports<'pkg/dictionary/mongodb-core'>;
}
declare module 'pkg/dictionary/mongodb.js' {
  declare module.exports: $Exports<'pkg/dictionary/mongodb'>;
}
declare module 'pkg/dictionary/mongoose.js' {
  declare module.exports: $Exports<'pkg/dictionary/mongoose'>;
}
declare module 'pkg/dictionary/mongoskin.js' {
  declare module.exports: $Exports<'pkg/dictionary/mongoskin'>;
}
declare module 'pkg/dictionary/ms.js' {
  declare module.exports: $Exports<'pkg/dictionary/ms'>;
}
declare module 'pkg/dictionary/msgpack.js' {
  declare module.exports: $Exports<'pkg/dictionary/msgpack'>;
}
declare module 'pkg/dictionary/multer.js' {
  declare module.exports: $Exports<'pkg/dictionary/multer'>;
}
declare module 'pkg/dictionary/muri.js' {
  declare module.exports: $Exports<'pkg/dictionary/muri'>;
}
declare module 'pkg/dictionary/native-or-bluebird.js' {
  declare module.exports: $Exports<'pkg/dictionary/native-or-bluebird'>;
}
declare module 'pkg/dictionary/natives.js' {
  declare module.exports: $Exports<'pkg/dictionary/natives'>;
}
declare module 'pkg/dictionary/nconf.js' {
  declare module.exports: $Exports<'pkg/dictionary/nconf'>;
}
declare module 'pkg/dictionary/nedb.js' {
  declare module.exports: $Exports<'pkg/dictionary/nedb'>;
}
declare module 'pkg/dictionary/negotiator.js' {
  declare module.exports: $Exports<'pkg/dictionary/negotiator'>;
}
declare module 'pkg/dictionary/newrelic.js' {
  declare module.exports: $Exports<'pkg/dictionary/newrelic'>;
}
declare module 'pkg/dictionary/nib.js' {
  declare module.exports: $Exports<'pkg/dictionary/nib'>;
}
declare module 'pkg/dictionary/nightmare.js' {
  declare module.exports: $Exports<'pkg/dictionary/nightmare'>;
}
declare module 'pkg/dictionary/node-forge.js' {
  declare module.exports: $Exports<'pkg/dictionary/node-forge'>;
}
declare module 'pkg/dictionary/node-libcurl.js' {
  declare module.exports: $Exports<'pkg/dictionary/node-libcurl'>;
}
declare module 'pkg/dictionary/node-notifier.js' {
  declare module.exports: $Exports<'pkg/dictionary/node-notifier'>;
}
declare module 'pkg/dictionary/node-pre-gyp.js' {
  declare module.exports: $Exports<'pkg/dictionary/node-pre-gyp'>;
}
declare module 'pkg/dictionary/node-redis-pubsub.js' {
  declare module.exports: $Exports<'pkg/dictionary/node-redis-pubsub'>;
}
declare module 'pkg/dictionary/node-sass.js' {
  declare module.exports: $Exports<'pkg/dictionary/node-sass'>;
}
declare module 'pkg/dictionary/node-uuid.js' {
  declare module.exports: $Exports<'pkg/dictionary/node-uuid'>;
}
declare module 'pkg/dictionary/node-xlsx.js' {
  declare module.exports: $Exports<'pkg/dictionary/node-xlsx'>;
}
declare module 'pkg/dictionary/node-zookeeper-client.js' {
  declare module.exports: $Exports<'pkg/dictionary/node-zookeeper-client'>;
}
declare module 'pkg/dictionary/nodegit.js' {
  declare module.exports: $Exports<'pkg/dictionary/nodegit'>;
}
declare module 'pkg/dictionary/nodemailer-sendmail-transport.js' {
  declare module.exports: $Exports<'pkg/dictionary/nodemailer-sendmail-transport'>;
}
declare module 'pkg/dictionary/nodemailer.js' {
  declare module.exports: $Exports<'pkg/dictionary/nodemailer'>;
}
declare module 'pkg/dictionary/npm-registry-client.js' {
  declare module.exports: $Exports<'pkg/dictionary/npm-registry-client'>;
}
declare module 'pkg/dictionary/npm.js' {
  declare module.exports: $Exports<'pkg/dictionary/npm'>;
}
declare module 'pkg/dictionary/nssocket.js' {
  declare module.exports: $Exports<'pkg/dictionary/nssocket'>;
}
declare module 'pkg/dictionary/oauth2orize.js' {
  declare module.exports: $Exports<'pkg/dictionary/oauth2orize'>;
}
declare module 'pkg/dictionary/octobat.js' {
  declare module.exports: $Exports<'pkg/dictionary/octobat'>;
}
declare module 'pkg/dictionary/opn.js' {
  declare module.exports: $Exports<'pkg/dictionary/opn'>;
}
declare module 'pkg/dictionary/optimist.js' {
  declare module.exports: $Exports<'pkg/dictionary/optimist'>;
}
declare module 'pkg/dictionary/passport-local.js' {
  declare module.exports: $Exports<'pkg/dictionary/passport-local'>;
}
declare module 'pkg/dictionary/passport.js' {
  declare module.exports: $Exports<'pkg/dictionary/passport'>;
}
declare module 'pkg/dictionary/pg-cursor.js' {
  declare module.exports: $Exports<'pkg/dictionary/pg-cursor'>;
}
declare module 'pkg/dictionary/pg-query-stream.js' {
  declare module.exports: $Exports<'pkg/dictionary/pg-query-stream'>;
}
declare module 'pkg/dictionary/pg-types.js' {
  declare module.exports: $Exports<'pkg/dictionary/pg-types'>;
}
declare module 'pkg/dictionary/pg.js' {
  declare module.exports: $Exports<'pkg/dictionary/pg'>;
}
declare module 'pkg/dictionary/pg.js.js' {
  declare module.exports: $Exports<'pkg/dictionary/pg.js'>;
}
declare module 'pkg/dictionary/pgpass.js' {
  declare module.exports: $Exports<'pkg/dictionary/pgpass'>;
}
declare module 'pkg/dictionary/phantom.js' {
  declare module.exports: $Exports<'pkg/dictionary/phantom'>;
}
declare module 'pkg/dictionary/phantomjs-prebuilt.js' {
  declare module.exports: $Exports<'pkg/dictionary/phantomjs-prebuilt'>;
}
declare module 'pkg/dictionary/pkginfo.js' {
  declare module.exports: $Exports<'pkg/dictionary/pkginfo'>;
}
declare module 'pkg/dictionary/pm2.js' {
  declare module.exports: $Exports<'pkg/dictionary/pm2'>;
}
declare module 'pkg/dictionary/pmx.js' {
  declare module.exports: $Exports<'pkg/dictionary/pmx'>;
}
declare module 'pkg/dictionary/pouchdb.js' {
  declare module.exports: $Exports<'pkg/dictionary/pouchdb'>;
}
declare module 'pkg/dictionary/primus-emitter.js' {
  declare module.exports: $Exports<'pkg/dictionary/primus-emitter'>;
}
declare module 'pkg/dictionary/primus-spark-latency.js' {
  declare module.exports: $Exports<'pkg/dictionary/primus-spark-latency'>;
}
declare module 'pkg/dictionary/primus.js' {
  declare module.exports: $Exports<'pkg/dictionary/primus'>;
}
declare module 'pkg/dictionary/publicsuffixlist.js' {
  declare module.exports: $Exports<'pkg/dictionary/publicsuffixlist'>;
}
declare module 'pkg/dictionary/pug.js' {
  declare module.exports: $Exports<'pkg/dictionary/pug'>;
}
declare module 'pkg/dictionary/punt.js' {
  declare module.exports: $Exports<'pkg/dictionary/punt'>;
}
declare module 'pkg/dictionary/puppeteer.js' {
  declare module.exports: $Exports<'pkg/dictionary/puppeteer'>;
}
declare module 'pkg/dictionary/pwd.js' {
  declare module.exports: $Exports<'pkg/dictionary/pwd'>;
}
declare module 'pkg/dictionary/q.js' {
  declare module.exports: $Exports<'pkg/dictionary/q'>;
}
declare module 'pkg/dictionary/raven.js' {
  declare module.exports: $Exports<'pkg/dictionary/raven'>;
}
declare module 'pkg/dictionary/rc.js' {
  declare module.exports: $Exports<'pkg/dictionary/rc'>;
}
declare module 'pkg/dictionary/readable-stream.js' {
  declare module.exports: $Exports<'pkg/dictionary/readable-stream'>;
}
declare module 'pkg/dictionary/rechoir.js' {
  declare module.exports: $Exports<'pkg/dictionary/rechoir'>;
}
declare module 'pkg/dictionary/redis-parser.js' {
  declare module.exports: $Exports<'pkg/dictionary/redis-parser'>;
}
declare module 'pkg/dictionary/redis.js' {
  declare module.exports: $Exports<'pkg/dictionary/redis'>;
}
declare module 'pkg/dictionary/regression.js' {
  declare module.exports: $Exports<'pkg/dictionary/regression'>;
}
declare module 'pkg/dictionary/reload.js' {
  declare module.exports: $Exports<'pkg/dictionary/reload'>;
}
declare module 'pkg/dictionary/request.js' {
  declare module.exports: $Exports<'pkg/dictionary/request'>;
}
declare module 'pkg/dictionary/require_optional.js' {
  declare module.exports: $Exports<'pkg/dictionary/require_optional'>;
}
declare module 'pkg/dictionary/require-uncached.js' {
  declare module.exports: $Exports<'pkg/dictionary/require-uncached'>;
}
declare module 'pkg/dictionary/s3.js' {
  declare module.exports: $Exports<'pkg/dictionary/s3'>;
}
declare module 'pkg/dictionary/safe_datejs.js' {
  declare module.exports: $Exports<'pkg/dictionary/safe_datejs'>;
}
declare module 'pkg/dictionary/sails.js' {
  declare module.exports: $Exports<'pkg/dictionary/sails'>;
}
declare module 'pkg/dictionary/sax.js' {
  declare module.exports: $Exports<'pkg/dictionary/sax'>;
}
declare module 'pkg/dictionary/scrypt.js' {
  declare module.exports: $Exports<'pkg/dictionary/scrypt'>;
}
declare module 'pkg/dictionary/semver.js' {
  declare module.exports: $Exports<'pkg/dictionary/semver'>;
}
declare module 'pkg/dictionary/sequelize.js' {
  declare module.exports: $Exports<'pkg/dictionary/sequelize'>;
}
declare module 'pkg/dictionary/serialport.js' {
  declare module.exports: $Exports<'pkg/dictionary/serialport'>;
}
declare module 'pkg/dictionary/sha3.js' {
  declare module.exports: $Exports<'pkg/dictionary/sha3'>;
}
declare module 'pkg/dictionary/sharp.js' {
  declare module.exports: $Exports<'pkg/dictionary/sharp'>;
}
declare module 'pkg/dictionary/shelljs.js' {
  declare module.exports: $Exports<'pkg/dictionary/shelljs'>;
}
declare module 'pkg/dictionary/sinon.js' {
  declare module.exports: $Exports<'pkg/dictionary/sinon'>;
}
declare module 'pkg/dictionary/socket.io-client.js' {
  declare module.exports: $Exports<'pkg/dictionary/socket.io-client'>;
}
declare module 'pkg/dictionary/socket.io.js' {
  declare module.exports: $Exports<'pkg/dictionary/socket.io'>;
}
declare module 'pkg/dictionary/sqlite3.js' {
  declare module.exports: $Exports<'pkg/dictionary/sqlite3'>;
}
declare module 'pkg/dictionary/steam-crypto.js' {
  declare module.exports: $Exports<'pkg/dictionary/steam-crypto'>;
}
declare module 'pkg/dictionary/steam-resources.js' {
  declare module.exports: $Exports<'pkg/dictionary/steam-resources'>;
}
declare module 'pkg/dictionary/steam.js' {
  declare module.exports: $Exports<'pkg/dictionary/steam'>;
}
declare module 'pkg/dictionary/stripe-webhook-middleware.js' {
  declare module.exports: $Exports<'pkg/dictionary/stripe-webhook-middleware'>;
}
declare module 'pkg/dictionary/stripe.js' {
  declare module.exports: $Exports<'pkg/dictionary/stripe'>;
}
declare module 'pkg/dictionary/strong-globalize.js' {
  declare module.exports: $Exports<'pkg/dictionary/strong-globalize'>;
}
declare module 'pkg/dictionary/stylus.js' {
  declare module.exports: $Exports<'pkg/dictionary/stylus'>;
}
declare module 'pkg/dictionary/supervisor.js' {
  declare module.exports: $Exports<'pkg/dictionary/supervisor'>;
}
declare module 'pkg/dictionary/tabtab.js' {
  declare module.exports: $Exports<'pkg/dictionary/tabtab'>;
}
declare module 'pkg/dictionary/tesseract.js.js' {
  declare module.exports: $Exports<'pkg/dictionary/tesseract.js'>;
}
declare module 'pkg/dictionary/throng.js' {
  declare module.exports: $Exports<'pkg/dictionary/throng'>;
}
declare module 'pkg/dictionary/time.js' {
  declare module.exports: $Exports<'pkg/dictionary/time'>;
}
declare module 'pkg/dictionary/tmp.js' {
  declare module.exports: $Exports<'pkg/dictionary/tmp'>;
}
declare module 'pkg/dictionary/transformers.js' {
  declare module.exports: $Exports<'pkg/dictionary/transformers'>;
}
declare module 'pkg/dictionary/uglify-js.js' {
  declare module.exports: $Exports<'pkg/dictionary/uglify-js'>;
}
declare module 'pkg/dictionary/umd.js' {
  declare module.exports: $Exports<'pkg/dictionary/umd'>;
}
declare module 'pkg/dictionary/underscore.js' {
  declare module.exports: $Exports<'pkg/dictionary/underscore'>;
}
declare module 'pkg/dictionary/union.js' {
  declare module.exports: $Exports<'pkg/dictionary/union'>;
}
declare module 'pkg/dictionary/update-notifier.js' {
  declare module.exports: $Exports<'pkg/dictionary/update-notifier'>;
}
declare module 'pkg/dictionary/usage.js' {
  declare module.exports: $Exports<'pkg/dictionary/usage'>;
}
declare module 'pkg/dictionary/v8flags.js' {
  declare module.exports: $Exports<'pkg/dictionary/v8flags'>;
}
declare module 'pkg/dictionary/verror.js' {
  declare module.exports: $Exports<'pkg/dictionary/verror'>;
}
declare module 'pkg/dictionary/voc.js' {
  declare module.exports: $Exports<'pkg/dictionary/voc'>;
}
declare module 'pkg/dictionary/winston-uber.js' {
  declare module.exports: $Exports<'pkg/dictionary/winston-uber'>;
}
declare module 'pkg/dictionary/winston.js' {
  declare module.exports: $Exports<'pkg/dictionary/winston'>;
}
declare module 'pkg/dictionary/ws.js' {
  declare module.exports: $Exports<'pkg/dictionary/ws'>;
}
declare module 'pkg/dictionary/xlsx.js' {
  declare module.exports: $Exports<'pkg/dictionary/xlsx'>;
}
declare module 'pkg/dictionary/xml2js.js' {
  declare module.exports: $Exports<'pkg/dictionary/xml2js'>;
}
declare module 'pkg/dictionary/yargs.js' {
  declare module.exports: $Exports<'pkg/dictionary/yargs'>;
}
declare module 'pkg/dictionary/zeromq.js' {
  declare module.exports: $Exports<'pkg/dictionary/zeromq'>;
}
declare module 'pkg/lib-es5/bin.js' {
  declare module.exports: $Exports<'pkg/lib-es5/bin'>;
}
declare module 'pkg/lib-es5/chmod.js' {
  declare module.exports: $Exports<'pkg/lib-es5/chmod'>;
}
declare module 'pkg/lib-es5/detector.js' {
  declare module.exports: $Exports<'pkg/lib-es5/detector'>;
}
declare module 'pkg/lib-es5/fabricator.js' {
  declare module.exports: $Exports<'pkg/lib-es5/fabricator'>;
}
declare module 'pkg/lib-es5/follow.js' {
  declare module.exports: $Exports<'pkg/lib-es5/follow'>;
}
declare module 'pkg/lib-es5/help.js' {
  declare module.exports: $Exports<'pkg/lib-es5/help'>;
}
declare module 'pkg/lib-es5/index.js' {
  declare module.exports: $Exports<'pkg/lib-es5/index'>;
}
declare module 'pkg/lib-es5/log.js' {
  declare module.exports: $Exports<'pkg/lib-es5/log'>;
}
declare module 'pkg/lib-es5/natives.js' {
  declare module.exports: $Exports<'pkg/lib-es5/natives'>;
}
declare module 'pkg/lib-es5/packer.js' {
  declare module.exports: $Exports<'pkg/lib-es5/packer'>;
}
declare module 'pkg/lib-es5/producer.js' {
  declare module.exports: $Exports<'pkg/lib-es5/producer'>;
}
declare module 'pkg/lib-es5/refiner.js' {
  declare module.exports: $Exports<'pkg/lib-es5/refiner'>;
}
declare module 'pkg/lib-es5/walker.js' {
  declare module.exports: $Exports<'pkg/lib-es5/walker'>;
}
declare module 'pkg/prelude/bootstrap.js' {
  declare module.exports: $Exports<'pkg/prelude/bootstrap'>;
}
declare module 'pkg/prelude/common.js' {
  declare module.exports: $Exports<'pkg/prelude/common'>;
}
