// flow-typed signature: 4b9c3081f258595d28636aedba2d2f7d
// flow-typed version: <<STUB>>/shebang-loader_v^0.0.1/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'shebang-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'shebang-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'shebang-loader/index' {
  declare module.exports: $Exports<'shebang-loader'>;
}
declare module 'shebang-loader/index.js' {
  declare module.exports: $Exports<'shebang-loader'>;
}
