// flow-typed signature: c93097ac72068ee95b5103a08266c83e
// flow-typed version: <<STUB>>/uniq_v^1.0.1/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'uniq'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'uniq' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'uniq/test/test' {
  declare module.exports: any;
}

declare module 'uniq/uniq' {
  declare module.exports: any;
}

// Filename aliases
declare module 'uniq/test/test.js' {
  declare module.exports: $Exports<'uniq/test/test'>;
}
declare module 'uniq/uniq.js' {
  declare module.exports: $Exports<'uniq/uniq'>;
}
