// flow-typed signature: 78420b63002248370215cab0933d5652
// flow-typed version: <<STUB>>/util.promisify_v^1.0.0/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'util.promisify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'util.promisify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'util.promisify/implementation' {
  declare module.exports: any;
}

declare module 'util.promisify/polyfill' {
  declare module.exports: any;
}

declare module 'util.promisify/shim' {
  declare module.exports: any;
}

// Filename aliases
declare module 'util.promisify/implementation.js' {
  declare module.exports: $Exports<'util.promisify/implementation'>;
}
declare module 'util.promisify/index' {
  declare module.exports: $Exports<'util.promisify'>;
}
declare module 'util.promisify/index.js' {
  declare module.exports: $Exports<'util.promisify'>;
}
declare module 'util.promisify/polyfill.js' {
  declare module.exports: $Exports<'util.promisify/polyfill'>;
}
declare module 'util.promisify/shim.js' {
  declare module.exports: $Exports<'util.promisify/shim'>;
}
